services:
  ros2-humble:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ros2-humble-fc
    environment:
      - DISPLAY=unix:1
      #- DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./ros2_ws:/root/ros2_ws #마운트 추가
    working_dir: /root/ros2_ws
    privileged: true
    network_mode: host
    ipc: host
    restart: always
    stdin_open: true
    tty: true

